### ISSUE TITLE
Generated equals can check if the argument is a reference to this object

### ISSUE THREAD

**Issue by orischwartz** [inferred/FreeBuilder#286]
Following up on #277 (#270), can add a small optimization to value type `equals` method to check if the input is the same instance as `this`:

https://github.com/inferred/FreeBuilder/blob/c247b0b03fdca39c87031934a028fcb110964ff7/src/main/java/org/inferred/freebuilder/processor/CodeGenerator.java#L390-L393

So generated code looks like:

```java
if (!(obj instanceof Type_Builder.Value)) {
  return false;
}
if (obj == this) {
  return true;
}
```

**Comment by chrisalice** [comment]
So the original reason this check wasn't in place is because many call sites actually already do this check (e.g. see Object.equals, HashSet.contains, etc.), and it makes the code cleaner. Now you raise it again, though, I'm less convinced: the cost of the check is minimal and the potential performance benefits are good. Can you provide evidence of an actual real-world case that would be improved? That would definitely settle the question.

**Comment by orischwartz** [comment]
Ah, had no idea, thanks for pointing that out. That is actually my only use-case, feel free to close.

[`HashMap#get`](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/util/HashMap.java#L322)
[`Objects.equals`](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/util/Objects.java#L57)

**Comment by chrisalice** [comment]
Closed pending concrete use-case that isn't already doing this optimization for us, as discussed.
